//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleExam.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
            this.CommentApplications = new HashSet<CommentApplication>();
            this.UserApplications = new HashSet<UserApplication>();
        }
    
        public int IDApplication { get; set; }
        public string ClientName { get; set; }
        public string PhoneClient { get; set; }
        public Nullable<int> StatusApp { get; set; }
        public Nullable<System.DateTime> DateOpenApp { get; set; }
        public Nullable<System.DateTime> DateCloseApp { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual StatusApplication StatusApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentApplication> CommentApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserApplication> UserApplications { get; set; }
    }
}
